### ISSUE TITLE
Cropping images

### ISSUE THREAD

**Issue by sairamrebbapragada** [mwaseema/Drone-Detection#12]
Sir, 

As the frame size is big and drone size is small, we are cropping the input frames into overlapping patches right.

Do we do this for only train frames or for test frames also?

Thank you.

**Comment by mwaseema** [comment]
Hi @sairamrebbapragada,

Thanks for reaching out with your question.

We are cropping the test frames as well. Testing code does the cropping automatically as can be seen from the following line in the testing code.

https://github.com/mwaseema/Drone-Detection/blob/14cf376fee5b6d7c3677a72c440c3e36de0e7128/test_model/spatial/test_and_score.py#L33

Please make sure to use the appropriate cropping.

`get_frame_and_ground_truth_crop` can be used to generate 9 overlapping crops while `get_frame_and_ground_truth_crop_4splits` function can be used to generate 4 overlapping crops.

**Comment by sairamrebbapragada** [comment]
Thank you for the clarification sir.
