### ISSUE TITLE
what is your mean of AP?

### ISSUE THREAD

**Issue by chriszxk** [mwaseema/Drone-Detection#13]
HI:

your research work is very excellent as a reference for us, 

could you tell me what is  your testing rule on AP, is it AP@iou0.5 or AP@0.5:0.95?

thanks.

**Comment by mwaseema** [comment]
Hi @chriszxk,

Thanks for reaching out regarding your confusion.

We've used AP@iou0.5.

Regards,

**Comment by chriszxk** [comment]
> Hi @chriszxk,
> 
> Thanks for reaching out regarding your confusion.
> 
> We've used AP@iou0.5.
> 
> Regards,

Hi, thank you for your kindly reply , so , is the evaluation AP@0.5 follow the rule of VOC2007 or VOC2012, or COCO? because the different rule will get different values.

**Comment by chriszxk** [comment]
> Hi @chriszxk,
> 
> Thanks for reaching out regarding your confusion.
> 
> We've used AP@iou0.5.
> 
> Regards,

Thank you for your kindly answer, I want to enquire anathor question, do you follow Voc2007 or Voc2012 rule, when you compute mAP@0.5? thank you in advance.

**Comment by mwaseema** [comment]
Hi @chriszxk,

Let me change your question a bit so it can be referenced if anyone else has the similar question.

Which interpolation was used?

- 11 point interpolation
- All point interpolation

I've used all point interpolation as it is the standard way of computing AP when following PASCAL VOC standard after 2010.

I hope this answered your question. If this was not what you asked, please elaborate your question a bit.

Regards,

**Comment by chriszxk** [comment]
> Hi @chriszxk,
> 
> Let me change your question a bit so it can be referenced if anyone else has the similar question.
> 
> Which interpolation was used?
> 
> * 11 point interpolation
> * All point interpolation
> 
> I've used all point interpolation as it is the standard way of computing AP when following PASCAL VOC standard after 2010.
> 
> I hope this answered your question. If this was not what you asked, please elaborate your question a bit.
> 
> Regards,

Thank you,
your answer perfectly solve my question.

Sincerely,
