### ISSUE TITLE
Question about Stage-1 Test & Stage-2 Cuboids

### ISSUE THREAD

**Issue by ghost** [mwaseema/Drone-Detection#16]
Hi @mwaseema ,

From issue #12 it seems we need to modify the code in `test_model/spatial/test_and_score` to create 9 crops of each frame for the testing of NPS dataset. But in this file there are still a lot of commented code and variables such as `pred_probability_1` and `pred_probabilities_2`, so do we need to uncomment all of these code and comment all current code? I'm working on the NPS dataset.

In addition, at the stage 2 when generating fixed sized cuboids for NPS dataset and running `tools/cuboids/volumes_with_tracking_of_generated_boxes_with_stabilization.py`, some frames can't be stabilized and the final generated cuboid masks of NPS dataset are all black squares like this:

<img width="767" alt="image" src="https://github.com/mwaseema/Drone-Detection/assets/112253685/8df734c2-5184-4f96-ba6c-683425458192">

And the masks after applying CRF looks normal:

<img width="769" alt="image" src="https://github.com/mwaseema/Drone-Detection/assets/112253685/6f802997-2566-40ae-82c8-b6448555bf24">

The variables in `volumes_with_tracking_of_generated_boxes_with_stabilization.py` are:
```python
...
boxes_json_folder = '/extension/user/drones_dataset/train_3d/Boxes_Custom'
frames_folder = '/extension/user/drones_dataset/train/NPS_Frames_Train'
mask_folder = '/extension/user/drones_dataset/train_3d/CRF_Masks'
output_folder = '/extension/user/drones_dataset/train_3d/NPS_Cuboids'
output_filename_prefix = ''

patch_dimensions = 100
volume_dimensions = 224
foreground_pixel_value = 1
random_patch_dimensions = False
...
```

I want to know what the generated cuboid masks should look like ?

Thanks for your reply!

Regards,

**Comment by mwaseema** [comment]
Hi @qtcs,

Thanks for reaching out.

For changing the number of crops, you'll only need to change corresponding functions. Other commented code was used for internal testing. There should be code for creating the splits and then merging those splits. Both those will need to be changed.

> In addition, at the stage 2 when generating fixed sized cuboids for NPS dataset and running tools/cuboids/volumes_with_tracking_of_generated_boxes_with_stabilization.py, some frames can't be stabilized and the final generated cuboid masks of NPS dataset are all black squares like this:

This is happening because of the following value:

```python
foreground_pixel_value = 1
```

> And the masks after applying CRF looks normal:

Because this code will be treating value other than 0 as 255.

I hope this is helpful.

Regards,
Waseem

**Comment by ghost** [comment]
Hi @mwaseema ,

Thank you very much for your reply.

If the code `tools/cuboids/volumes_with_tracking_of_generated_boxes_with_stabilization.py` generates all  masks 
 in my `train_3d/Fixed_Cuboids/masks` are pure black , so according to your explanation the result I got is normal right?

Also lately I carefully read your paper, but I've been stuck at this stage of I3D features. I don't really understand the parameter configuration in the code `train/temporal/config.py`:

```python
...
# absolute folder path
my_base_path = "/extension/user"
dataset_base_path = "drones_dataset"

dataset_base_path = os.path.join(my_base_path, dataset_base_path)

model_used = '3D'

dataset_links = {
    'train': {
        # folder where annotation masks are stored
        'annotations': os.path.join(dataset_base_path, 'train_3d', 'Fixed_Cuboids', 'masks'),
        # folder where I3D features are stored
        'images': os.path.join(dataset_base_path, 'train_3d', 'kinetics-i3d', 'data', 'checkpoints', 'rgb_imagenet'),
        # folder where to save model weights after every epoch
        'temp': os.path.join(dataset_base_path, 'temp_3d', model_used, model_used),
    },
}
...
```

Is the `annotations` path parameter should be the masks folder generated by **Fixed sized cuboids** step, or it should be the masks folder that after **CRF on the candidate boxes**, which is the binary masks after applying CRF ?

Also, as for the `images` path parameter, what data of I3D repo is essentially we need? I set the `images` parameter of this folder : https://github.com/google-deepmind/kinetics-i3d/tree/master/data/checkpoints/rgb_imagenet, but the `train_model.py` code seems not work and got some errors:

```bash
Starting Epoch  0
Epoch 1/1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/drones_detections/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/user/miniconda3/envs/drones_detections/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/miniconda3/envs/drones_detections/lib/python3.6/site-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
  File "/home/user/miniconda3/envs/drones_detections/lib/python3.6/site-packages/keras_segmentation-0.2.0-py3.6.egg/keras_segmentation/data_utils/data_loader.py", line 435, in image_segmentation_generator_i3d
    im, seg = next(zipped)
StopIteration

Traceback (most recent call last):
  File "temporal/train_model.py", line 39, in <module>
    main()
  File "temporal/train_model.py", line 32, in main
    steps_per_epoch=steps_per_epoch,
  File "/home/user/miniconda3/envs/drones_detections/lib/python3.6/site-packages/keras_segmentation-0.2.0-py3.6.egg/keras_segmentation/train.py", line 866, in train_i3d
  File "/home/user/miniconda3/envs/drones_detections/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/drones_detections/lib/python3.6/site-packages/keras/engine/training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
StopIteration
...
```

So I suspect there is something wrong with the parameters I set inside `train/temporal/config.py`. I've been stuck at this step for a long time lately, and I'd appreciate your help!

Best regards,
