### ISSUE TITLE
NPS dataset download

### ISSUE THREAD

**Issue by wpfhtl** [mwaseema/Drone-Detection#2]
Thanks for the releasing of this impressing work. I have a small question, where to download the NPS dataset? Would you please help to provide a link for it? Many thanks.

**Comment by mwaseema** [comment]
You can download NPS drones dataset from the following link:
https://engineering.purdue.edu/~bouman/UAV_Dataset/

**Comment by wpfhtl** [comment]
Thanks a lot.

**Comment by feifeiwei** [comment]
NPS-Drones-Dataset's labels with this repo are different from [this labels](https://engineering.purdue.edu/~bouman/UAV_Dataset), why??

**Comment by mwaseema** [comment]
@feifeiwei we've improved the original annotations by annotating almost all of the frames within the dataset using a tool which gave output in the format we have within our repository. Also, we've reformatted filenames a little as well.

Please refer to [Annotation Format](https://github.com/mwaseema/Drone-Detection#format) section on readme for details on how to read these annotation files.
