### ISSUE TITLE
Question for real-time performance

### ISSUE THREAD

**Issue by Ahmetf1** [mwaseema/Drone-Detection#3]
Hello, thanks for this great work !

Have you tried the model on real-time object detection problem ?
If so, how was the performance ?
I am searching for a model to run on jetson for real-time drone detection.

Thank you in advance

**Comment by mwaseema** [comment]
Hi Ahmetf1,

Thanks for reaching out. Regarding your question, it won't be real-time if you want to use both stages. One stage can give more FPS but at the cost of a slight accuracy drop. Based on your dataset nature, stage 1 can perform really well. Also, you can reduce the number of patches per image to 4 to improve FPS. This will depend on your dataset's nature. You'll have to run it on jetson for performance evaluation.

Regards,
Waseem

**Comment by Ahmetf1** [comment]
Thanks for your helpful advice. I will share the result if a give it a try.
