### ISSUE TITLE
predict_segmentation 

### ISSUE THREAD

**Issue by SherlockMoriaty** [mwaseema/Drone-Detection#4]
I have read your paper and code. I think it's an amazing and interesting job. There were some problems running the code you provided.
The function named predict_segmentation appears frequently in your code, but I can't find its definition. And the statements using it always report errors as follows:
ValueError: too many values to unpack (expected 2)
such as 
[segm_pred_1, segm_pred_2], [pred_probability_1, pred_probability_2] = model.predict_segmentation(inp = img_crop)
at line about 40 in the file ./test_model/spatial/test_and_score.py.
I would appreciate it if you could take the time to answer my question.

**Comment by SherlockMoriaty** [comment]
and what is 'i3d features' in test_model/temporal/config.py？ i have problems in getting them. and I would appreciate it if you could take the time to provide a more direct or detailed way to get it. I am looking forward to your early reply. thank you

**Comment by mwaseema** [comment]
Hi SherlockMoriaty,

`predict_segmentation` is being set to `predict_with_weighted_output` in the following file of the dependency package at line 305. Clicking on following link will take you there. \
https://github.com/mwaseema/image-segmentation-keras-implementation/blob/e137b55c3a19787309f086744e3f7ed1b4df4520/keras_segmentation/models/model_utils.py#L305

`predict_with_weighted_output` is defined in following file at line 181. \
https://github.com/mwaseema/image-segmentation-keras-implementation/blob/e137b55c3a19787309f086744e3f7ed1b4df4520/keras_segmentation/predict.py#L181

`model.predict_segmentation` outputs a tuple having two lists. Both lists have two elements each (two segmentation outputs and two probability outputs). There is no way for this function to be giving something different if you followed the readme and didn't change any code.

```python
[segm_pred_1, segm_pred_2], [pred_probability_1, pred_probability_2] = model.predict_segmentation(
                                                                                                inp=img_crop
                                                                                            )
```

But let's debug what is causing this issue. Can you please change the above line as follows and inspect the output for its dimensions.

```python
model_outputs = model.predict_segmentation(inp=img_crop)
```

You can use something like this to debug what is withing the output:
```python
print("type(model_outputs)", type(model_outputs))
print("len(model_outputs)", len(model_outputs))
print("type(model_outputs[0])", type(model_outputs[0]))
print("len(model_outputs[0])", len(model_outputs[0]))
print("type(model_outputs[1])", type(model_outputs[1]))
print("len(model_outputs[1])", len(model_outputs[1]))
```

And post it here as well so I can let you know what can be the reason.

You can also use something like this to save the complete output as a file and attach it with your comment:

```python
np.save('/folder/path/to/save.npy', model_outputs)
```

Regarding the **i3d features** in `test_model/temporal/config.py`, please have a look on the readme's **I3D features** section https://github.com/mwaseema/Drone-Detection#i3d-features

Regards,
