### ISSUE TITLE
Fl-Drones dataset

### ISSUE THREAD

**Issue by Sairam13001** [mwaseema/Drone-Detection#6]
This work is awesome. I am trying to run the code and understand your work in detail.

Could you kindly let me know from where I can download FL-Drones dataset.

**Comment by mwaseema** [comment]
Hi Sairam,

We had requested access to FL-Drones dataset from authors of following paper:
https://arxiv.org/abs/1411.7715

Please request them to share the data with you.

Regards,

**Comment by Sairam13001** [comment]
Sure, Thank you.
