### ISSUE TITLE
Question regarding "foreground_in_mask"

### ISSUE THREAD

**Issue by Sairam13001** [mwaseema/Drone-Detection#7]
Hai sir, I am working with NPS-Drones dataset. 

I have a doubt regarding why we have to set "foreground_in_mask = 1" while training.

In tools/video_to_frames_and_masks.py, when we use "ret, frame = video_cap.read()", the pixel values in the frames are in the range [0, 255] and not [0,1].

So, if we set foreground_in_mask = 1, then all the masks will be just black images right. 

Please correct me if I am missing something.

**Comment by mwaseema** [comment]
Hi Sairam,

1 is label for the prediction and not the value for image itself.

Hope this helps.

Regards,

**Comment by Sairam13001** [comment]
Yeah Yeah... I understood sir. Thank you.
