### ISSUE TITLE
Error while testing on NPS-Drones-Dataset

### ISSUE THREAD

**Issue by Sairam13001** [mwaseema/Drone-Detection#8]
Sir, I am working with NPS drones dataset. 

I followed the readme file and successfully ran the training code for 100 epochs. 

In "tools/video_to_frames_and_masks.py", I set "foreground_in_mask" as 1 for training data and 255 for testing data.

While testing, using the "test_and_score.py", I am getting the following error:

**********************************************************************************************************************************
Predicting results: 100%|        3091/3091 [37:16<00:00,  1.38frame/s]
Generating text annotation files: 100%|      3091/3091 [01:25<00:00, 36.18image/s]
Generating text annotation files for ground truth: 100%|             3091/3091 [01:24<00:00, 36.77image/s]
Synchronising files: 100%|      3091/3091 [00:02<00:00, 1430.37file/s]

Traceback (most recent call last):
  File "/home/ai20resch13001/Drone-Detection/tools/object_detection_metrics/my_evaluation_metric_code/evaluation_code.py", line 227, in <module>
    method=MethodAveragePrecision.EveryPointInterpolation)  # As the official matlab code
  File "/home/ai20resch13001/Drone-Detection/tools/object_detection_metrics/lib/Evaluator.py", line 96, in GetPascalVOCMetrics
    dects = sorted(dects, key=lambda conf: conf[2], reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
Processing checkpoints: 100%|         1/1 [40:15<00:00, 2415.96s/it]
***************************************************************************************************************************************

I am trying to debug this error but couldn't do it yet. 

Could you kindly let me know what might have caused this.

Thank you.

**Comment by mwaseema** [comment]
Hi Sairam,

There is None value within your predictions or maybe some ground truth. One reason for this could be non existing frame or ground truth file as well.
Code file `tools/object-detection-metrics/my_evaluation_metric_code/evaluation_code.py` is being called within `test_and_score.py` file. You can run this file directly with appropriate arguments in debug mode and stop execution where exception is raised to see what can be causing this issue.

Hope this helps you find the issue.

Regards,
